<?php namespace JF;
/**

Copyright 2020 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-36f204
Date:    2020-03-30 17:48:04
Version: v3.0.3
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-36f204",
    "email": {
        "to": "pacho@gmail.com",
        "cc": "",
        "bcc": "",
        "subject": "Contacto formulario COVID-19",
        "template": "",
        "skipEmptyFields": false
    },
    "admin": {
        "users": "gema_pina@cpm.coop:20201903,pacho@minds.com.mx:Pacho2015\/*",
        "dataDelivery": "emailAndFile"
    },
    "thankyou": {
        "url": "https:\/\/cpm.coop",
        "message": "Gracias {f1}, tu informaci\u00f3n se ha enviado exitosamente, este es el n\u00famero de referencia de tu consulta {AutoID}.\n\nNos comunicaremos contigo cuanto antes sea posible.\n\nGracias por tu paciencia.",
        "seconds": "10"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "{f2}",
        "template": "Dear {f1},\n\nGracias por llenar el formulario de ayuda. Te enviamos una copia de los datos enviados, reiterando que jam\u00e1s ser\u00e1n compartidos ni expuestos sin tu consentimietno previo:\n{dataTable}\n\nTe contactaremos cuanto antes sea psoible.\n\nNuestros mejores deseos.\n{HTTP_HOST}\n\n\nReference ID: {AutoID}\nYour IP: {IP}\nDate: {Date}\nTime: {Time}\n"
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "green"
        },
        "Select2": {
            "enabled": false
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "Nombre completo:",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Este campo es obligatorio."
                    },
                    "equalto": {
                        "enabled": false
                    },
                    "maxlength": {
                        "enabled": false
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": ""
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "N\u00famero de socio:",
            "field_type": "number",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "numSpinner": {
                    "enabled": false
                },
                "validators": {
                    "number": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Es necesario ingresar su n\u00famero de socio."
                    }
                },
                "placeholder": "",
                "addon": {
                    "leftIcon": "",
                    "leftText": ""
                }
            },
            "id": "f4",
            "cid": "c26"
        },
        {
            "label": "Correo:",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Es necesario ingresar su correo."
                    },
                    "maxlength": {
                        "enabled": false
                    }
                },
                "addon": {
                    "leftIcon": "",
                    "leftText": ""
                }
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "Tel\u00e9fono:",
            "field_type": "phone",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "sender": true,
                "placeholder": "XX-XXXX-XXXX",
                "addon": {
                    "leftIcon": ""
                },
                "validators": {
                    "pattern": {
                        "enabled": true,
                        "val": "[0-9 -+.]+",
                        "msg": "Formato inv\u00e1lido"
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Es necesario ingresar su tel\u00e9fono."
                    },
                    "phonenumber": {
                        "enabled": false
                    }
                }
            },
            "phone": {
                "validationMethod": "simple",
                "simpleFormat": "xxx-xxx-xxxx",
                "usePhoneLib": "N"
            },
            "id": "f5",
            "cid": "c35"
        },
        {
            "label": "Motivo:",
            "field_type": "paragraph",
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true,
                        "msg": "Es necesario exponer el motivo de su solicitud."
                    }
                },
                "addon": {
                    "leftIcon": ""
                }
            },
            "id": "f3",
            "cid": "c3"
        },
        {
            "label": "",
            "field_type": "checkboxes",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Consulta nuestro aviso de privacidad.",
                        "checked": false
                    }
                ],
                "validators": {
                    "minlength": {
                        "msg": "Please select at least {0} option(s)",
                        "enabled": false
                    },
                    "maxlength": {
                        "msg": "Please select no more than {0} option(s)",
                        "enabled": false
                    },
                    "required": {
                        "enabled": true,
                        "msg": "Es necesario aceptar de conformidad."
                    }
                },
                "presetJson": "",
                "style": {
                    "columns": "inline"
                },
                "hidden": false
            },
            "id": "f6",
            "cid": "c34",
            "labelHide": true
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "Enviar informaci\u00f3n",
                "icon": "",
                "checkRequiredFields": "Por favor, revisa que todos los campos est\u00e9n llenados correctamente"
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "always"
    },
    "licenseKey": ""
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class